# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb37fc37e91ccac2e0bd14e2df1f1d4b2303b235ca69fee709fbc5f70abf6aa78d225005ac6ed968cf0fc5b85694269ff6355cd13fa6ed403886c93da8f192b3

test:
  secret_key_base: 9a848f96e2077f9faeef90a5d4d972c87190aa1fc71580ffad314b270e8d342245f5a663813a355e15a249f5b59a321747b508ee61e99aa4d387ccf5799b2773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
